            
def configure(ctx):
    ctx.recurse('l1')
    ctx.recurse('l2')
    ctx.recurse('l2_5')
    ctx.recurse('l3')
    ctx.recurse('l4')
    ctx.recurse('basic_dependencies')

def build(ctx):
    pass


    
     
