# This test attaches the meaningless kwarg bar into the views for tracking
# purposes only.

def configure(ctx):
    ctx.SFFUnits.add(bar='default')
    ctx.SFFUnits.addview('basic_views','foo',bar='foo')

